// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Model.DepartamentDetailsModel.DepartamentDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("departament_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("text_json")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("departament_id");

                    b.HasIndex("status_id");

                    b.ToTable("departament_details_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.DepartamentDetailsModel.DepartamentDetailTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("departament_detail_id")
                        .HasColumnType("integer");

                    b.Property<int?>("departament_translation_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("text_json")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("departament_detail_id");

                    b.HasIndex("departament_translation_id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_translation_id");

                    b.ToTable("departament_details_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsModel.Departament", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("crated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("departament_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool?>("favorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("img_id")
                        .HasColumnType("integer");

                    b.Property<int?>("parent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("position")
                        .HasColumnType("integer");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("title_short")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("departament_type_id");

                    b.HasIndex("img_id");

                    b.HasIndex("status_id");

                    b.ToTable("departament_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsModel.DepartamentTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("crated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("departament_translation_type_id")
                        .HasColumnType("integer");

                    b.Property<int?>("departament_type_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool?>("favorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("img_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("parent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("position")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("title_short")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("departament_translation_type_id");

                    b.HasIndex("img_id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_translation_id");

                    b.HasIndex("user_id");

                    b.ToTable("departament_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsTypeModel.DepartamentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("status_id");

                    b.ToTable("departament_types_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsTypeModel.DepartamentTypeTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("departament_type_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("departament_type_id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_translation_id");

                    b.ToTable("departament_types_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.FileModel.Files", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("crated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("status_id");

                    b.HasIndex("user_id");

                    b.ToTable("files_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.FileModel.FilesTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("files_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("files_id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_translation_id");

                    b.ToTable("files_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.GenderModel.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("status_id");

                    b.ToTable("genders_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.GenderModel.GenderTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<int?>("gender_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("gender_id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_translation_id");

                    b.ToTable("genders_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.LanguagesModel.Language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("languages")
                        .HasColumnType("text");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("status_id");

                    b.ToTable("languages_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.PagesModel.PageTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("crated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool?>("favorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("img_translation_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("page_id")
                        .HasColumnType("integer");

                    b.Property<int?>("position")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("title_short")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("img_translation_id");

                    b.HasIndex("language_id");

                    b.HasIndex("page_id");

                    b.HasIndex("status_translation_id");

                    b.HasIndex("user_id");

                    b.ToTable("pages_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.PagesModel.Pages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("crated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool?>("favorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("img_id")
                        .HasColumnType("integer");

                    b.Property<int?>("position")
                        .HasColumnType("integer");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("title_short")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("img_id");

                    b.HasIndex("status_id");

                    b.HasIndex("user_id");

                    b.ToTable("pages_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.PersonModel.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fathers_name")
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<int?>("gender_id")
                        .HasColumnType("integer");

                    b.Property<int?>("img_id")
                        .HasColumnType("integer");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<string>("passport_number")
                        .HasColumnType("text");

                    b.Property<string>("passport_text")
                        .HasColumnType("text");

                    b.Property<string>("pinfl")
                        .HasColumnType("text");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("gender_id");

                    b.HasIndex("img_id");

                    b.HasIndex("status_id");

                    b.ToTable("persons_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.PersonModel.PersonTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("fathers_name")
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<int?>("gender_id")
                        .HasColumnType("integer");

                    b.Property<int?>("img_id")
                        .HasColumnType("integer");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<int?>("persons_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("gender_id");

                    b.HasIndex("img_id");

                    b.HasIndex("language_id");

                    b.HasIndex("persons_id");

                    b.HasIndex("status_translation_id");

                    b.ToTable("persons_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.StatusModel.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("statuses_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.StatusModel.StatusTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_id");

                    b.ToTable("statuses_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("departament_id")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("person_id")
                        .HasColumnType("integer");

                    b.Property<bool?>("removed")
                        .HasColumnType("boolean");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("user_type_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("departament_id")
                        .IsUnique();

                    b.HasIndex("login")
                        .IsUnique();

                    b.HasIndex("person_id");

                    b.HasIndex("status_id");

                    b.HasIndex("user_type_id");

                    b.ToTable("users_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.UserType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("status_id");

                    b.ToTable("user_types_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.UserTypeTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("language_id")
                        .HasColumnType("integer");

                    b.Property<int?>("status_translation_id")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.Property<int>("user_types_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("language_id");

                    b.HasIndex("status_translation_id");

                    b.HasIndex("user_types_id");

                    b.ToTable("user_types_translations_20ts24tu");
                });

            modelBuilder.Entity("Entities.Model.DepartamentDetailsModel.DepartamentDetail", b =>
                {
                    b.HasOne("Entities.Model.DepartamentsModel.Departament", "departament_")
                        .WithMany()
                        .HasForeignKey("departament_id");

                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("departament_");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.DepartamentDetailsModel.DepartamentDetailTranslation", b =>
                {
                    b.HasOne("Entities.Model.DepartamentDetailsModel.DepartamentDetail", "departament_detail_")
                        .WithMany()
                        .HasForeignKey("departament_detail_id");

                    b.HasOne("Entities.Model.DepartamentsModel.DepartamentTranslation", "departament_translation_")
                        .WithMany()
                        .HasForeignKey("departament_translation_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.Navigation("departament_detail_");

                    b.Navigation("departament_translation_");

                    b.Navigation("language_");

                    b.Navigation("status_translation_");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsModel.Departament", b =>
                {
                    b.HasOne("Entities.Model.DepartamentsTypeModel.DepartamentType", "departament_type_")
                        .WithMany()
                        .HasForeignKey("departament_type_id");

                    b.HasOne("Entities.Model.FileModel.Files", "img_")
                        .WithMany()
                        .HasForeignKey("img_id");

                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("departament_type_");

                    b.Navigation("img_");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsModel.DepartamentTranslation", b =>
                {
                    b.HasOne("Entities.Model.DepartamentsTypeModel.DepartamentTypeTranslation", "departament_translation_type_")
                        .WithMany()
                        .HasForeignKey("departament_translation_type_id");

                    b.HasOne("Entities.Model.FileModel.FilesTranslation", "img_")
                        .WithMany()
                        .HasForeignKey("img_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.HasOne("Entities.Model.User", "user_")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("departament_translation_type_");

                    b.Navigation("img_");

                    b.Navigation("language_");

                    b.Navigation("status_translation_");

                    b.Navigation("user_");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsTypeModel.DepartamentType", b =>
                {
                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsTypeModel.DepartamentTypeTranslation", b =>
                {
                    b.HasOne("Entities.Model.DepartamentsTypeModel.DepartamentType", "departament_type_")
                        .WithMany()
                        .HasForeignKey("departament_type_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.Navigation("departament_type_");

                    b.Navigation("language_");

                    b.Navigation("status_translation_");
                });

            modelBuilder.Entity("Entities.Model.FileModel.Files", b =>
                {
                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.HasOne("Entities.Model.User", "user_")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("status_");

                    b.Navigation("user_");
                });

            modelBuilder.Entity("Entities.Model.FileModel.FilesTranslation", b =>
                {
                    b.HasOne("Entities.Model.FileModel.Files", "files_")
                        .WithMany()
                        .HasForeignKey("files_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.Navigation("files_");

                    b.Navigation("language_");

                    b.Navigation("status_translation_");
                });

            modelBuilder.Entity("Entities.Model.GenderModel.Gender", b =>
                {
                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.GenderModel.GenderTranslation", b =>
                {
                    b.HasOne("Entities.Model.GenderModel.Gender", "gender_")
                        .WithMany()
                        .HasForeignKey("gender_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.Navigation("gender_");

                    b.Navigation("language_");

                    b.Navigation("status_translation_");
                });

            modelBuilder.Entity("Entities.Model.LanguagesModel.Language", b =>
                {
                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.PagesModel.PageTranslation", b =>
                {
                    b.HasOne("Entities.Model.FileModel.FilesTranslation", "img_translation_")
                        .WithMany()
                        .HasForeignKey("img_translation_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.PagesModel.Pages", "page_")
                        .WithMany()
                        .HasForeignKey("page_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.HasOne("Entities.Model.User", "user_")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("img_translation_");

                    b.Navigation("language_");

                    b.Navigation("page_");

                    b.Navigation("status_translation_");

                    b.Navigation("user_");
                });

            modelBuilder.Entity("Entities.Model.PagesModel.Pages", b =>
                {
                    b.HasOne("Entities.Model.FileModel.Files", "img_")
                        .WithMany()
                        .HasForeignKey("img_id");

                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.HasOne("Entities.Model.User", "user_")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("img_");

                    b.Navigation("status_");

                    b.Navigation("user_");
                });

            modelBuilder.Entity("Entities.Model.PersonModel.Person", b =>
                {
                    b.HasOne("Entities.Model.GenderModel.Gender", "gender_")
                        .WithMany()
                        .HasForeignKey("gender_id");

                    b.HasOne("Entities.Model.FileModel.Files", "img_")
                        .WithMany()
                        .HasForeignKey("img_id");

                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("gender_");

                    b.Navigation("img_");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.PersonModel.PersonTranslation", b =>
                {
                    b.HasOne("Entities.Model.GenderModel.GenderTranslation", "gender_")
                        .WithMany()
                        .HasForeignKey("gender_id");

                    b.HasOne("Entities.Model.FileModel.FilesTranslation", "img_")
                        .WithMany()
                        .HasForeignKey("img_id");

                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.PersonModel.Person", "persons_")
                        .WithMany()
                        .HasForeignKey("persons_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.Navigation("gender_");

                    b.Navigation("img_");

                    b.Navigation("language_");

                    b.Navigation("persons_");

                    b.Navigation("status_translation_");
                });

            modelBuilder.Entity("Entities.Model.StatusModel.StatusTranslation", b =>
                {
                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("language_");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.User", b =>
                {
                    b.HasOne("Entities.Model.DepartamentsModel.Departament", "departament_")
                        .WithOne("user_")
                        .HasForeignKey("Entities.Model.User", "departament_id");

                    b.HasOne("Entities.Model.PersonModel.Person", "person_")
                        .WithMany()
                        .HasForeignKey("person_id");

                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.HasOne("Entities.Model.UserType", "user_type_")
                        .WithMany()
                        .HasForeignKey("user_type_id");

                    b.Navigation("departament_");

                    b.Navigation("person_");

                    b.Navigation("status_");

                    b.Navigation("user_type_");
                });

            modelBuilder.Entity("Entities.Model.UserType", b =>
                {
                    b.HasOne("Entities.Model.StatusModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.UserTypeTranslation", b =>
                {
                    b.HasOne("Entities.Model.LanguagesModel.Language", "language_")
                        .WithMany()
                        .HasForeignKey("language_id");

                    b.HasOne("Entities.Model.StatusModel.StatusTranslation", "status_translation_")
                        .WithMany()
                        .HasForeignKey("status_translation_id");

                    b.HasOne("Entities.Model.UserType", "user_types_")
                        .WithMany()
                        .HasForeignKey("user_types_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("language_");

                    b.Navigation("status_translation_");

                    b.Navigation("user_types_");
                });

            modelBuilder.Entity("Entities.Model.DepartamentsModel.Departament", b =>
                {
                    b.Navigation("user_");
                });
#pragma warning restore 612, 618
        }
    }
}
