using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Entities.Model.DistrictsModel;

namespace Entities.Configuration
{
    public class DistrictConfiguration : IEntityTypeConfiguration<District>
    {
        public void Configure(EntityTypeBuilder<District> builder)
        {
            builder.HasData(
                new District { id = 1, territorie_id = 8, status_id = 1, title = "Boʻzatov tumani" },
                new District { id = 3, territorie_id = 14, status_id = 1, title = "Bandixon tumani" },
                new District { id = 4, territorie_id = 16, status_id = 1, title = "Tuproqqal''a tumani" },
                new District { id = 10, territorie_id = 8, status_id = 1, title = "Nukus shahar" },
                new District { id = 12, territorie_id = 8, status_id = 1, title = "Amudaryo tumani" },
                new District { id = 13, territorie_id = 8, status_id = 1, title = "Beruniy tumani" },
                new District { id = 14, territorie_id = 8, status_id = 1, title = "Qonlikoʻl tumani" },
                new District { id = 15, territorie_id = 8, status_id = 1, title = "Qoraoʻzak tumani" },
                new District { id = 16, territorie_id = 8, status_id = 1, title = "Kegeyli tumani" },
                new District { id = 17, territorie_id = 8, status_id = 1, title = "Qoʻngʻirot tumani" },
                new District { id = 18, territorie_id = 8, status_id = 1, title = "Muynoq tumani" },
                new District { id = 19, territorie_id = 8, status_id = 1, title = "Nukus tumani" },
                new District { id = 20, territorie_id = 8, status_id = 1, title = "Taxtakoʻprik tumani" },
                new District { id = 21, territorie_id = 8, status_id = 1, title = "Toʻrtkoʻl tumani" },
                new District { id = 22, territorie_id = 8, status_id = 1, title = "Xoʻjayli tumani" },
                new District { id = 23, territorie_id = 8, status_id = 1, title = "Chimboy tumani" },
                new District { id = 24, territorie_id = 8, status_id = 1, title = "Shoʻmanay tumani" },
                new District { id = 25, territorie_id = 8, status_id = 1, title = "Ellikqal''a tumani" },
                new District { id = 26, territorie_id = 9, status_id = 1, title = "Buxoro shahar" },
                new District { id = 27, territorie_id = 9, status_id = 1, title = "Buxoro tuman" },
                new District { id = 28, territorie_id = 9, status_id = 1, title = "Vobkent tuman" },
                new District { id = 29, territorie_id = 9, status_id = 1, title = "Gʻijduvon tuman" },
                new District { id = 30, territorie_id = 9, status_id = 1, title = "Jondor tuman" },
                new District { id = 32, territorie_id = 9, status_id = 1, title = "Kogon tuman" },
                new District { id = 33, territorie_id = 9, status_id = 1, title = "Olot tuman" },
                new District { id = 34, territorie_id = 9, status_id = 1, title = "Peshku tuman" },
                new District { id = 35, territorie_id = 9, status_id = 1, title = "Romitan tuman" },
                new District { id = 36, territorie_id = 9, status_id = 1, title = "Shofirkon tuman" },
                new District { id = 37, territorie_id = 9, status_id = 1, title = "Qorakoʻl tuman" },
                new District { id = 38, territorie_id = 9, status_id = 1, title = "Qorovulbozor tuman" },
                new District { id = 39, territorie_id = 10, status_id = 1, title = "Samarqand shahar" },
                new District { id = 40, territorie_id = 10, status_id = 1, title = "Oqdaryo tumani" },
                new District { id = 41, territorie_id = 10, status_id = 1, title = "Bulungʻur tumani" },
                new District { id = 42, territorie_id = 10, status_id = 1, title = "Jomboy tumani" },
                new District { id = 43, territorie_id = 10, status_id = 1, title = "Kattaqoʻrgʻon tumani" },
                new District { id = 44, territorie_id = 10, status_id = 1, title = "Kattaqoʻrgʻon shahar" },
                new District { id = 45, territorie_id = 10, status_id = 1, title = "Qoʻshrabod tumani" },
                new District { id = 46, territorie_id = 10, status_id = 1, title = "Narpay tumani" },
                new District { id = 47, territorie_id = 10, status_id = 1, title = "Nurobod tumani" },
                new District { id = 48, territorie_id = 10, status_id = 1, title = "Payariq tumani" },
                new District { id = 49, territorie_id = 10, status_id = 1, title = "Pastdargʻom tumani" },
                new District { id = 50, territorie_id = 10, status_id = 1, title = "Paxtachi tumani" },
                new District { id = 51, territorie_id = 10, status_id = 1, title = "Samarqand tumani" },
                new District { id = 53, territorie_id = 10, status_id = 1, title = "Tayloq tumani" },
                new District { id = 54, territorie_id = 10, status_id = 1, title = "Urgut tumani" },
                new District { id = 55, territorie_id = 11, status_id = 1, title = "Navoiy shahar" },
                new District { id = 56, territorie_id = 11, status_id = 1, title = "Karmana tumani" },
                new District { id = 57, territorie_id = 11, status_id = 1, title = "Navbaxor tumani" },
                new District { id = 58, territorie_id = 11, status_id = 1, title = "Nurota tumani - Gʻozgʻon shahri" },
                new District { id = 59, territorie_id = 11, status_id = 1, title = "Xatirchi tumani" },
                new District { id = 60, territorie_id = 11, status_id = 1, title = "Qiziltepa tumani" },
                new District { id = 61, territorie_id = 11, status_id = 1, title = "Konimex tumani" },
                new District { id = 62, territorie_id = 11, status_id = 1, title = "Uchquduq tumani" },
                new District { id = 63, territorie_id = 11, status_id = 1, title = "Zarafshon shahar" },
                new District { id = 64, territorie_id = 11, status_id = 1, title = "Tomdi tumani" },
                new District { id = 65, territorie_id = 12, status_id = 1, title = "Andijon shahar" },
                new District { id = 66, territorie_id = 12, status_id = 1, title = "Xonobod shahar" },
                new District { id = 67, territorie_id = 12, status_id = 1, title = "Andijon tumani" },
                new District { id = 68, territorie_id = 12, status_id = 1, title = "Asaka tumani" },
                new District { id = 69, territorie_id = 12, status_id = 1, title = "Baliqchi tumani" },
                new District { id = 70, territorie_id = 12, status_id = 1, title = "Boʻz tumani" },
                new District { id = 71, territorie_id = 12, status_id = 1, title = "Buloqboshi tumani" },
                new District { id = 72, territorie_id = 12, status_id = 1, title = "Jalolquduq tumani" },
                new District { id = 73, territorie_id = 12, status_id = 1, title = "Izboskan tumani" },
                new District { id = 74, territorie_id = 12, status_id = 1, title = "Ulugʻnor tumani" },
                new District { id = 75, territorie_id = 12, status_id = 1, title = "Qoʻrgʻontepa tumani" },
                new District { id = 76, territorie_id = 12, status_id = 1, title = "Marxamat tumani" },
                new District { id = 77, territorie_id = 12, status_id = 1, title = "Oltinkoʻl tumani" },
                new District { id = 78, territorie_id = 12, status_id = 1, title = "Paxtaobod tumani" },
                new District { id = 79, territorie_id = 12, status_id = 1, title = "Hoʻjaobod tumani" },
                new District { id = 80, territorie_id = 12, status_id = 1, title = "Shaxrixon tumani" },
                new District { id = 82, territorie_id = 13, status_id = 1, title = "Margʻilon shahar" },
                new District { id = 83, territorie_id = 13, status_id = 1, title = "Fargʻona shahar" },
                new District { id = 84, territorie_id = 13, status_id = 1, title = "Quvasoy shahar" },
                new District { id = 85, territorie_id = 13, status_id = 1, title = "Qoʻqon shahar" },
                new District { id = 86, territorie_id = 13, status_id = 1, title = "Bogʻdod tumani" },
                new District { id = 87, territorie_id = 13, status_id = 1, title = "Beshariq tumani" },
                new District { id = 88, territorie_id = 13, status_id = 1, title = "Buvayda tumani" },
                new District { id = 89, territorie_id = 13, status_id = 1, title = "Dangʻara tumani" },
                new District { id = 90, territorie_id = 13, status_id = 1, title = "Yozyovon tumani" },
                new District { id = 91, territorie_id = 13, status_id = 1, title = "Oltiariq tumani" },
                new District { id = 92, territorie_id = 13, status_id = 1, title = "Qoʻshtepa tumani" },
                new District { id = 93, territorie_id = 13, status_id = 1, title = "Rishton tumani" },
                new District { id = 94, territorie_id = 13, status_id = 1, title = "Soʻx tumani" },
                new District { id = 95, territorie_id = 13, status_id = 1, title = "Toshloq tumani" },
                new District { id = 96, territorie_id = 13, status_id = 1, title = "Uchkoʻprik tumani" },
                new District { id = 97, territorie_id = 13, status_id = 1, title = "Fargʻona tumani" },
                new District { id = 98, territorie_id = 13, status_id = 1, title = "Furqat tumani" },
                new District { id = 99, territorie_id = 13, status_id = 1, title = "Oʻzbekiston tumani" },
                new District { id = 100, territorie_id = 13, status_id = 1, title = "Quva tumani" },
                new District { id = 101, territorie_id = 14, status_id = 1, title = "Angor tumani" },
                new District { id = 102, territorie_id = 14, status_id = 1, title = "Boysun tumani" },
                new District { id = 103, territorie_id = 14, status_id = 1, title = "Denov tumani" },
                new District { id = 104, territorie_id = 14, status_id = 1, title = "Jarqoʻrgʻon tumani" },
                new District { id = 105, territorie_id = 14, status_id = 1, title = "Qiziriq tumani" },
                new District { id = 106, territorie_id = 14, status_id = 1, title = "Qumqoʻrgʻon tumani" },
                new District { id = 107, territorie_id = 14, status_id = 1, title = "Muzrabot tumani" },
                new District { id = 108, territorie_id = 14, status_id = 1, title = "Oltinsoy tumani" },
                new District { id = 109, territorie_id = 14, status_id = 1, title = "Sariosiyo tumani" },
                new District { id = 110, territorie_id = 14, status_id = 1, title = "Termiz tumani" },
                new District { id = 111, territorie_id = 14, status_id = 1, title = "Termiz shahar" },
                new District { id = 112, territorie_id = 14, status_id = 1, title = "Uzun tumani" },
                new District { id = 113, territorie_id = 14, status_id = 1, title = "Sherobod tumani" },
                new District { id = 114, territorie_id = 14, status_id = 1, title = "Shoʻrchi tumani" },
                new District { id = 115, territorie_id = 15, status_id = 1, title = "Oqoltin tumani" },
                new District { id = 116, territorie_id = 15, status_id = 1, title = "Boyovut tumani" },
                new District { id = 117, territorie_id = 15, status_id = 1, title = "Guliston tumani" },
                new District { id = 118, territorie_id = 15, status_id = 1, title = "Mirzaobod tumani" },
                new District { id = 119, territorie_id = 15, status_id = 1, title = "Sayxunobod tumani" },
                new District { id = 120, territorie_id = 15, status_id = 1, title = "Sirdaryo tumani" },
                new District { id = 121, territorie_id = 15, status_id = 1, title = "Sardoba tumani" },
                new District { id = 122, territorie_id = 15, status_id = 1, title = "Xovos tumani" },
                new District { id = 123, territorie_id = 15, status_id = 1, title = "Guliston shahar" },
                new District { id = 124, territorie_id = 15, status_id = 1, title = "Shirin shahar" },
                new District { id = 126, territorie_id = 15, status_id = 1, title = "Yangier shahar" },
                new District { id = 127, territorie_id = 16, status_id = 1, title = "Urganch shahar" },
                new District { id = 128, territorie_id = 16, status_id = 1, title = "Bogʻot tumani" },
                new District { id = 129, territorie_id = 16, status_id = 1, title = "Gurlan tumani" },
                new District { id = 130, territorie_id = 16, status_id = 1, title = "Xozarasp tumani" },
                new District { id = 131, territorie_id = 16, status_id = 1, title = "Xiva tumani" },
                new District { id = 132, territorie_id = 16, status_id = 1, title = "Xonqa tumani" },
                new District { id = 133, territorie_id = 16, status_id = 1, title = "Urganch tumani" },
                new District { id = 134, territorie_id = 16, status_id = 1, title = "Qoʻshkoʻpir tumani" },
                new District { id = 135, territorie_id = 16, status_id = 1, title = "Shovot tumani" },
                new District { id = 136, territorie_id = 16, status_id = 1, title = "Yangiariq tumani" },
                new District { id = 137, territorie_id = 16, status_id = 1, title = "Yangibozor tumani" },
                new District { id = 138, territorie_id = 17, status_id = 1, title = "Angren shahar" },
                new District { id = 139, territorie_id = 17, status_id = 1, title = "Bekobod shahar" },
                new District { id = 140, territorie_id = 17, status_id = 1, title = "Olmaliq shahar" },
                new District { id = 141, territorie_id = 17, status_id = 1, title = "Chirchiq shahar" },
                new District { id = 142, territorie_id = 17, status_id = 1, title = "Bekobod tumani" },
                new District { id = 143, territorie_id = 17, status_id = 1, title = "Boʻka tumani" },
                new District { id = 144, territorie_id = 17, status_id = 1, title = "Boʻstonliq tumani" },
                new District { id = 145, territorie_id = 17, status_id = 1, title = "Qibray tumani" },
                new District { id = 146, territorie_id = 17, status_id = 1, title = "Zangiota tumani" },
                new District { id = 148, territorie_id = 17, status_id = 1, title = "Quyichirchiq tumani" },
                new District { id = 149, territorie_id = 17, status_id = 1, title = "Oqqoʻrgʻon tumani" },
                new District { id = 150, territorie_id = 17, status_id = 1, title = "Oxongaron tumani" },
                new District { id = 151, territorie_id = 17, status_id = 1, title = "Parkent tumani" },
                new District { id = 152, territorie_id = 17, status_id = 1, title = "Pskent tumani" },
                new District { id = 153, territorie_id = 17, status_id = 1, title = "Oʻrtachirchiq tumani - Yangihayot tumani" },
                new District { id = 154, territorie_id = 17, status_id = 1, title = "Chinoz tumani" },
                new District { id = 155, territorie_id = 17, status_id = 1, title = "Yuqorichirchiq tumani" },
                new District { id = 156, territorie_id = 17, status_id = 1, title = "Yangiyoʻl tumani - Yangihayot tumani" },
                new District { id = 158, territorie_id = 18, status_id = 1, title = "Qarshi shahar" },
                new District { id = 159, territorie_id = 18, status_id = 1, title = "Gʻuzor tumani" },
                new District { id = 160, territorie_id = 18, status_id = 1, title = "Qarshi tumani" },
                new District { id = 161, territorie_id = 18, status_id = 1, title = "Kasbi tumani" },
                new District { id = 162, territorie_id = 18, status_id = 1, title = "Koson tumani" },
                new District { id = 163, territorie_id = 18, status_id = 1, title = "Kitob tumani" },
                new District { id = 164, territorie_id = 18, status_id = 1, title = "Mirishkor tumani" },
                new District { id = 165, territorie_id = 18, status_id = 1, title = "Muborak tumani" },
                new District { id = 166, territorie_id = 18, status_id = 1, title = "Nishon tumani" },
                new District { id = 167, territorie_id = 18, status_id = 1, title = "Chiroqchi tumani" },
                new District { id = 168, territorie_id = 18, status_id = 1, title = "Shaxrisabz tumani" },
                new District { id = 170, territorie_id = 18, status_id = 1, title = "Qamashi tumani" },
                new District { id = 171, territorie_id = 18, status_id = 1, title = "Dexqonobod tumani" },
                new District { id = 172, territorie_id = 18, status_id = 1, title = "Yakkabogʻ tumani" },
                new District { id = 173, territorie_id = 19, status_id = 1, title = "Jizzax shahar" },
                new District { id = 174, territorie_id = 19, status_id = 1, title = "Baxmal tumani" },
                new District { id = 175, territorie_id = 19, status_id = 1, title = "Doʻstlik tumani" },
                new District { id = 176, territorie_id = 19, status_id = 1, title = "Gʻallaorol tumani" },
                new District { id = 177, territorie_id = 19, status_id = 1, title = "Sh.Rashidov tumani" },
                new District { id = 178, territorie_id = 19, status_id = 1, title = "Zarbdor tumani" },
                new District { id = 179, territorie_id = 19, status_id = 1, title = "Zafarobod tumani" },
                new District { id = 180, territorie_id = 19, status_id = 1, title = "Zomin tumani" },
                new District { id = 181, territorie_id = 19, status_id = 1, title = "Paxtakor tumani" },
                new District { id = 182, territorie_id = 19, status_id = 1, title = "Mirzachoʻl tumani" },
                new District { id = 183, territorie_id = 19, status_id = 1, title = "Forish tumani" },
                new District { id = 184, territorie_id = 19, status_id = 1, title = "Yangiobod tumani" },
                new District { id = 185, territorie_id = 21, status_id = 1, title = "Namangan shahar" },
                new District { id = 186, territorie_id = 21, status_id = 1, title = "Mingbuloq tumani" },
                new District { id = 189, territorie_id = 21, status_id = 1, title = "Pop tumani" },
                new District { id = 190, territorie_id = 21, status_id = 1, title = "Norin tumani" },
                new District { id = 191, territorie_id = 21, status_id = 1, title = "Toʻraqoʻrgʻon tumani" },
                new District { id = 192, territorie_id = 21, status_id = 1, title = "Uychi tumani" },
                new District { id = 194, territorie_id = 21, status_id = 1, title = "Chortoq tumani" },
                new District { id = 195, territorie_id = 21, status_id = 1, title = "Chust tumani" },
                new District { id = 196, territorie_id = 21, status_id = 1, title = "Yangiqoʻrgʻon tumani" },
                new District { id = 198, territorie_id = 22, status_id = 1, title = "Yunusobod tumani" },
                new District { id = 199, territorie_id = 22, status_id = 1, title = "Mirobod tumani" },
                new District { id = 200, territorie_id = 22, status_id = 1, title = "Yakkasaroy tumani" },
                new District { id = 201, territorie_id = 22, status_id = 1, title = "Olmazor tumani" },
                new District { id = 202, territorie_id = 22, status_id = 1, title = "Bektemir tumani - Yangihayot tumani" },
                new District { id = 203, territorie_id = 22, status_id = 1, title = "Yashnobod tumani" },
                new District { id = 204, territorie_id = 22, status_id = 1, title = "Chilonzor tumani" },
                new District { id = 205, territorie_id = 22, status_id = 1, title = "Uchtepa tumani" },
                new District { id = 207, territorie_id = 22, status_id = 1, title = "Mirzo Ulugʻbek tumani" },
                new District { id = 208, territorie_id = 22, status_id = 1, title = "Sergeli tumani - Yangihayot tumani" },
                new District { id = 209, territorie_id = 10, status_id = 1, title = "Ishtixon tumani" },
                new District { id = 210, territorie_id = 9, status_id = 1, title = "Kogon shahar" },
                new District { id = 211, territorie_id = 19, status_id = 1, title = "Arnasoy tumani" },
                new District { id = 212, territorie_id = 22, status_id = 1, title = "Shayxontoxur tumani" },
                new District { id = 214, territorie_id = 21, status_id = 1, title = "Namangan tumani" },
                new District { id = 215, territorie_id = 21, status_id = 1, title = "Uchqoʻrgʻon tumani" },
                new District { id = 216, territorie_id = 21, status_id = 1, title = "Kosonsoy tumani" },
                new District { id = 217, territorie_id = 16, status_id = 1, title = "Xiva shahar" },
                new District { id = 218, territorie_id = 8, status_id = 1, title = "Taxiatosh" },
                new District { id = 219, territorie_id = 18, status_id = 1, title = "Shaxrisabz shahar" },
                new District { id = 220, territorie_id = 17, status_id = 1, title = "Toshkent tumani" },
                new District { id = 221, territorie_id = 17, status_id = 1, title = "Yangiyoʻl shahar" },
                new District { id = 222, territorie_id = 17, status_id = 1, title = "Ohangaron shahar" },
                new District { id = 223, territorie_id = 17, status_id = 1, title = "Nurafshon shahar" }
                );

        }
    }
}
